In [55]:
import os, sys, time, h5py, zipfile
import numpy as np
import pandas as pd

In [56]:
behav_data = pd.read_csv('/home/anna/Scrivania/NeuroHackademy2019/unrestricted_annatruzzi91_8_5_2019_13_21_16.csv')

In [57]:
behav_data.keys()

Index(['Subject', 'Release', 'Acquisition', 'Gender', 'Age',
       '3T_Full_MR_Compl', 'T1_Count', 'T2_Count', '3T_RS-fMRI_Count',
       '3T_RS-fMRI_PctCompl',
       ...
       'Noise_Comp', 'Odor_Unadj', 'Odor_AgeAdj', 'PainIntens_RawScore',
       'PainInterf_Tscore', 'Taste_Unadj', 'Taste_AgeAdj', 'Mars_Log_Score',
       'Mars_Errs', 'Mars_Final'],
      dtype='object', length=582)

In [58]:
age = behav_data[['Subject','Age']]

In [59]:
min_age_vector=[]
max_age_vector=[]
for item in age['Age']:
    if '+' in item:
        min_age_vector.append(int(item[0:2]))
        max_age_vector.append(90)
    else:
        min_age_vector.append(int(item[0:2]))
        max_age_vector.append(int(item[-2:]))

min_age_vector=np.asarray(min_age_vector)
max_age_vector=np.asarray(max_age_vector)

In [60]:
min_age_vector

array([22, 26, 26, ..., 26, 22, 26])

In [61]:
unique, counts = np.unique(min_age_vector, return_counts=True)
dict(zip(unique, counts))
agelist = unique

In [62]:
age_category = np.zeros(shape=len(age['Age']))

In [63]:
age['min_age'] = pd.Series(min_age_vector)
age['age_category'] = pd.Series(age_category)

/home/anna/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/anna/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [64]:
age

      Subject    Age  min_age  age_category
0      100004  22-25       22           0.0
1      100206  26-30       26           0.0
2      100307  26-30       26           0.0
3      100408  31-35       31           0.0
4      100610  26-30       26           0.0
5      101006  31-35       31           0.0
6      101107  22-25       22           0.0
7      101208  31-35       31           0.0
8      101309  26-30       26           0.0
9      101410  26-30       26           0.0
10     101612  26-30       26           0.0
11     101915  31-35       31           0.0
12     102008  22-25       22           0.0
13     102109  26-30       26           0.0
14     102311  26-30       26           0.0
15     102513  26-30       26           0.0
16     102614  22-25       22           0.0
17     102715  26-30       26           0.0
18     102816  26-30       26           0.0
19     103010  22-25       22           0.0
20     103111  26-30       26           0.0
21     103212  31-35       31           0.0
22     103414  22-25       22           0.0
23     103515  26-30       26           0.0
24     103818  31-35       31           0.0
25     104012  26-30       26           0.0
26     104113  26-30       26           0.0
27     104416  31-35       31           0.0
28     104820    36+       36           0.0
29     105014  26-30       26           0.0
...       ...    ...      ...           ...
1176   953764  31-35       31           0.0
1177   955465  26-30       26           0.0
1178   957974  26-30       26           0.0
1179   958976  26-30       26           0.0
1180   959069  31-35       31           0.0
1181   959574  26-30       26           0.0
1182   962058  26-30       26           0.0
1183   965367  31-35       31           0.0
1184   965771  31-35       31           0.0
1185   966975  22-25       22           0.0
1186   969476  31-35       31           0.0
1187   970764  22-25       22           0.0
1188   971160  26-30       26           0.0
1189   972566  31-35       31           0.0
1190   973770  22-25       22           0.0
1191   978578  31-35       31           0.0
1192   979984  31-35       31           0.0
1193   983773  26-30       26           0.0
1194   984472  26-30       26           0.0
1195   987074  22-25       22           0.0
1196   987983  26-30       26           0.0
1197   989987  31-35       31           0.0
1198   990366  22-25       22           0.0
1199   991267  26-30       26           0.0
1200   992673  31-35       31           0.0
1201   992774  31-35       31           0.0
1202   993675  26-30       26           0.0
1203   994273  26-30       26           0.0
1204   995174  22-25       22           0.0
1205   996782  26-30       26           0.0

[1206 rows x 4 columns]

In [72]:
age.loc[age['min_age'] == agelist[0],['age_category']] = 0
age.loc[age['min_age'] == agelist[1],['age_category']] = 1
age.loc[age['min_age'] == agelist[2],['age_category']] = 2
age.loc[age['min_age'] == agelist[3],['age_category']] = 3

In [73]:
age

      Subject    Age  min_age  age_category
0      100004  22-25       22           0.0
1      100206  26-30       26           1.0
2      100307  26-30       26           1.0
3      100408  31-35       31           2.0
4      100610  26-30       26           1.0
5      101006  31-35       31           2.0
6      101107  22-25       22           0.0
7      101208  31-35       31           2.0
8      101309  26-30       26           1.0
9      101410  26-30       26           1.0
10     101612  26-30       26           1.0
11     101915  31-35       31           2.0
12     102008  22-25       22           0.0
13     102109  26-30       26           1.0
14     102311  26-30       26           1.0
15     102513  26-30       26           1.0
16     102614  22-25       22           0.0
17     102715  26-30       26           1.0
18     102816  26-30       26           1.0
19     103010  22-25       22           0.0
20     103111  26-30       26           1.0
21     103212  31-35       31           2.0
22     103414  22-25       22           0.0
23     103515  26-30       26           1.0
24     103818  31-35       31           2.0
25     104012  26-30       26           1.0
26     104113  26-30       26           1.0
27     104416  31-35       31           2.0
28     104820    36+       36           3.0
29     105014  26-30       26           1.0
...       ...    ...      ...           ...
1176   953764  31-35       31           2.0
1177   955465  26-30       26           1.0
1178   957974  26-30       26           1.0
1179   958976  26-30       26           1.0
1180   959069  31-35       31           2.0
1181   959574  26-30       26           1.0
1182   962058  26-30       26           1.0
1183   965367  31-35       31           2.0
1184   965771  31-35       31           2.0
1185   966975  22-25       22           0.0
1186   969476  31-35       31           2.0
1187   970764  22-25       22           0.0
1188   971160  26-30       26           1.0
1189   972566  31-35       31           2.0
1190   973770  22-25       22           0.0
1191   978578  31-35       31           2.0
1192   979984  31-35       31           2.0
1193   983773  26-30       26           1.0
1194   984472  26-30       26           1.0
1195   987074  22-25       22           0.0
1196   987983  26-30       26           1.0
1197   989987  31-35       31           2.0
1198   990366  22-25       22           0.0
1199   991267  26-30       26           1.0
1200   992673  31-35       31           2.0
1201   992774  31-35       31           2.0
1202   993675  26-30       26           1.0
1203   994273  26-30       26           1.0
1204   995174  22-25       22           0.0
1205   996782  26-30       26           1.0

[1206 rows x 4 columns]